kind: pipeline
name: default

steps:
- name: master-build  
  image: node:carbon-alpine
  commands:
    - npm config set registry http://registry.npm.taobao.org/
    - npm install
    - npm run build
    - npm config set registry https://registry.npmjs.org/
  when:
    branch:
      - master
    event: [push]

- name: master-docker  
  image: plugins/docker
  settings:
    registry: 172.20.10.3:8082
    mirror: http://hub-mirror.c.163.com
    username: simple
    password: admin123
    dockerfile: ./Dockerfile
    repo: 172.20.10.3:8082/${DRONE_REPO_NAME}
    tags: ${DRONE_COMMIT_BRANCH}-${DRONE_BUILD_NUMBER}
    insecure: true
  when:
    branch:
      - master
    event: [push]

- name: master-deploy  
  image: appleboy/drone-ssh
  settings:
    host:
      - 172.20.10.3
    username: double
    password:
      from_secret: ssh_secret
    port: 22
    command_timeout: 2m
    script:
      - docker pull 172.20.10.3:8082/${DRONE_REPO_NAME}:${DRONE_COMMIT_BRANCH}-${DRONE_BUILD_NUMBER}
      - docker run --rm -d -p 80:80/tcp 172.20.10.3:8082/${DRONE_REPO_NAME}:${DRONE_COMMIT_BRANCH}-${DRONE_BUILD_NUMBER}