kind: pipeline
name: default

steps:
- name: master-build  
  image: node:carbon-alpine
  commands:
    - npm install
    - npm run build
  when:
    branch:
      - master
    event: [push]

- name: master-docker  
  image: plugins/docker
  settings:
    registry: 172.20.10.3:8082
    username: simple
    password: admin123
    dockerfile: ./Dockerfile
    repo: 172.20.10.3:8082/${DRONE_REPO_NAME}
    tags: ${DRONE_COMMIT_BRANCH}-${DRONE_BUILD_NUMBER}
    insecure: true
  when:
    branch:
      - master
    event: [push]
